config/routes.rb
Rails.application.routes.draw do

  root 'topics#index'

  resources :categories
  resources :topics do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topics, dependent: :delete_all
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :category
  has_many :comments, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
     @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.topic_id = params[:topic_id]

    if @comment.save
      redirect_to topic_path(@comment.topic_id)
    else
      render :new
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to topic_path(params[:topic_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :content)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show
    @categories = Category.all
    @comment = Comment.new
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to @topic
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:author, :updater, :title, :content, :category_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title)
    title.blank? ? "KoKo-ToPi" : "#{title} | KoKo-ToPi"
  end
end

app/views/categories/_form.html.slim
= form_for @category do |f|
  .field
    = f.label :name, 'カテゴリ名'
    = f.text_field :name
  = f.submit

app/views/categories/_form.slim
= form_for @category do |f|
  .field
    = f.label :name, 'カテゴリ名'
    = f.text_field :name

app/views/categories/edit.html.slim
- provide(:title, 'カテゴリ編集')

h2 カテゴリ編集

== render 'form'

= link_to '一覧', categories_path
'|
= link_to '戻る', category_path

app/views/categories/edit.slim
h1 KoKo-ToPi

h2 カテゴリ編集

== render 'form'

app/views/categories/index.html.slim
- provide(:title, 'カテゴリ一覧')

h2 カテゴリ一覧
ul
  - @categories.each do |category|
    li = link_to category.name, category

= link_to '新規作成', new_category_path

app/views/categories/index.slim
h1 KoKo-ToPi

h2 カテゴリ一覧
ul
  - @categories.each do |category|
    li = category.name

app/views/categories/new.html.slim
- provide(:title, 'カテゴリ新規作成')

h2 カテゴリ新規作成

== render 'form'

= link_to '一覧', categories_path

app/views/categories/new.slim
h1 KoKo-ToPi

h2 カテゴリ新規作成

== render 'form'

app/views/categories/show.html.slim
- provide(:title, @category.name)

h2 = @category.name

table
  tr
    th 関連トピック
  - @category.topics.each do |topic|
    tr
      td = link_to topic.title, topic

br

small
  = 'カテゴリ作成日時: '
  = @category.created_at.strftime('%Y/%m/%d %H:%M')

br

small
  = 'カテゴリ更新日時: '
  = @category.updated_at.strftime('%Y/%m/%d %H:%M')

br

= link_to '戻る', categories_path
'|
= link_to '編集', edit_category_path
'|
= link_to '削除', @category, data: { confirm: '本当に削除しますか' }, method: :delete

app/views/categories/show.slim
h1 KoKo-ToPi

h2 = @category.name

table
  tr
    th 関連トピック
  - @category.topics.each do |topic|
    tr
      td = topic.title

br

small
  = 'カテゴリ作成日時: '
  = @category.created_at.strftime('%Y/%m/%d %H:%M')

br

small
  = 'カテゴリ更新日時: '
  = @category.updated_at.strftime('%Y/%m/%d %H:%M')

br

= link_to '削除', @category, data: { confirm: '本当に削除しますか' }, method: :delete

app/views/layouts/application.html.slim
DOCTYPE
html
  head
    title = page_title(yield(:title))
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    nav
      ul
        li = link_to 'トピック', topics_path
        li = link_to 'カテゴリー', categories_path
    .clear_b

    == yield

app/views/topics/_comment_form.html.slim
= form_for @comment, url: topic_comments_path(@topic) do |f|
  table
    tr
      th = f.label :author, '投稿者'
      td = f.text_field :author
    tr
      th = f.label :content, '本文'
      td = f.text_area :content
    tr
      th = 
      td = f.submit
br

app/views/topics/_edit_topic_form.html.slim
= form_for @topic do |f|
  table
    tr
      th = f.label :updater, '更新者'
      td = f.text_field :updater
    tr
      th = f.label :title, 'タイトル'
      td = f.text_field :title
    tr
      th = f.label :content, '本文'
      td = f.text_field :content
    tr
      th = f.label :category_id, 'カテゴリ'
      td = f.collection_select :category_id, Category.all, :id, :name
    tr
      th
      td = f.submit

app/views/topics/_form.html.slim
= form_for @comment do |f|
  table
    tr
      th = f.label :author, '投稿者'
      td = f.text_field :author
    tr
      th = f.label :content, '本文'
      td = f.text_area :content
    tr
      th = 
      td = f.submit class: 'btn btn-primary'

app/views/topics/_new_topic_form.html.slim
= form_for @topic do |f|
  table
    tr
      th = f.label :author, '投稿者'
      td = f.text_field :author
    tr
      th = f.label :title, 'タイトル'
      td = f.text_field :title
    tr
      th = f.label :content, '本文'
      td = f.text_field :content
    tr
      th = f.label :category_id, 'カテゴリ'
      td = f.collection_select :category_id, Category.all, :id, :name
    tr
      th
      td = f.submit

app/views/topics/_sidebar.html.slim
h2 カテゴリ一覧
ul
  - @categories.each do |category|
    li = link_to category.name, category

hr

app/views/topics/_sidebar_form.html.slim
h2 カテゴリ一覧
ul
  - @categories.each do |category|
    li = link_to category.name, category

hr

app/views/topics/edit.html.slim
- provide(:title, 'トピック編集')

h2 トピック編集

== render 'edit_topic_form'

= link_to '一覧', topics_path
'|
= link_to '戻る', topic_path

app/views/topics/index.html.slim
aside
  == render 'sidebar'

article
  h2 トピック一覧
  - @categories.each do |category|
    h3 = category.name
    ul
      - category.topics.each do |topic|
        li
          = link_to topic.title, topic
          = "コメント数(#{topic.comments.count})"
          br
          small = topic.created_at.strftime('%Y/%m/%d %H:%M')

  = link_to '新規作成', new_topic_path

app/views/topics/new.html.slim
- provide(:title, 'トピック新規作成')

h2 トピック新規作成

== render 'new_topic_form'

= link_to '一覧', topics_path

app/views/topics/show.html.slim
- provide(:title, @topic.title)

aside
  == render 'sidebar'

article
  h2 = @topic.title
  p = @topic.content
  small
    = 'トピック作成 '
    = @topic.created_at.strftime('%Y/%m/%d %H:%M')
    = @topic.author
  br
  small
    = 'トピック更新 '
    = @topic.updated_at.strftime('%Y/%m/%d %H:%M')
    = @topic.updater
  br
  = link_to '戻る', topics_path
  '|
  = link_to '編集', edit_topic_path
  '|
  = link_to '削除', @topic, data: { confirm: '本当に削除しますか' }, method: :delete

  hr

  == render 'comment_form'

  hr
    - @topic.comments.each do |comment|
      table
        tr
          th = '投稿者'
          td = comment.author
        tr
          th = '本文'
          td = comment.content
        tr
          th
            small = '投稿日時'
          td
            small = @topic.created_at.strftime('%Y/%m/%d %H:%M')
          td = link_to '削除', topic_comment_path(@topic, comment), data: { confirm: '本当に削除しますか' }, method: :delete
      hr

app/views/welcome/index.slim
h1 KoKo-ToPi

h2 カテゴリ一覧
/ link_to で飛ばしたい
ul
  - @categories.each do |category|
    li = category.name

hr

h2 トピック一覧
- @categories.each do |category|
  h3 = category.name
  ul
    - category.topics.each do |topic|
      li
        = "#{topic.title} コメント数(#{topic.comments.count})"
        br
        small = topic.created_at.strftime('%Y/%m/%d %H:%M')